version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres_turkey_parcel
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - turkey-parcel-db:/var/lib/postgressql/data
volumes:
  turkey-parcel-db:
    driver: local